version: 0.2

phases:
  pre_build:
    commands:
      - IMAGE_NAME="${REPOSITORY_URI}:$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} | head -c 7)"
  build:
    commands:
      - echo "do nothing."
  post_build:
    commands:
      - printf '{"Parameters":{"ProjectID":"%s","DockerImage":"%s"}}' ${PROJECT_ID} ${IMAGE_NAME} > config.json

artifacts:
  files: config.json
